
name: 'Choreo Deployer'
description: 'Deploy newly built docker images to kubernetes through the Choreo API'
author: WSO2
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
runs:
  using: node16
  main: index.js
